### ISSUE TITLE
一直显示 ajax listObjects.action succeed but JSON.parse failed

### ISSUE THREAD

**Issue by Wuvomi** [YXuuan/hfs4OSS#10]
弄了一个通宵+一个早上，反反复复检查了很多次配置文件，可是不知道为什么配置完一直显示错误。

还有，注意到一个小细节就是OSS的配置文件（oss.config.php）已经从 json 改成了php，这点在安装说明里面一直没有提到，我反复检查错误的时候把配置文件后续更改为json，但是错误依旧。

ajax listObjects.action succeed but JSON.parse failed
Go FLUCKING to check the console!

**Comment by YXuuan** [comment]
浏览器按F12呼出Console复制一下错误信息贴上来，这一步是服务器返回的数据不能正确被格式化为文件列表

**Comment by Wuvomi** [comment]
main.js:79 listObjects("", name, true) 
Cookies: {"passwords":{"index":"爱"}}
main.js:90 listObjects: FAILED
AccessDenied: The bucket you access does not belong to you. RequestId: 5E15DF3C7FFDC23535A9DBCB
<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function getObjectList() on null in /www/wwwroot/sweetymovie.club/app/action/listObjects.action.php:53
Stack trace:
#0 {main}
  thrown in <b>/www/wwwroot/sweetymovie.club/app/action/listObjects.action.php</b> on line <b>53</b><br />

main.js:96 SyntaxError: Unexpected token l in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.success (main.js:93)
    at u (jquery-3.3.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.3.1.min.js:2)
    at k (jquery-3.3.1.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery-3.3.1.min.js:2)
success @ main.js:96

**Comment by YXuuan** [comment]
向阿里云oss请求的时候出错了，提示的是你请求的bucket不是属于你的。检查一下oss.config.php里的配置，看看是不是用了别人的或者你自己ak/sk的权限没给足

**Comment by Wuvomi** [comment]
可是这个配置我用在Cloudreve上是通过的，可以正常使用。

**Comment by Wuvomi** [comment]
我看了一下Github的配置说明里面提到OSS的配置文件使用的是 oss.config.json
但是最新的源文件里面变成了 oss.config.php

这个跟文件名有关系吗？
