### ISSUE TITLE
能够介绍一下部署的需要的环境吗

### ISSUE THREAD

**Issue by tihu2016** [YXuuan/hfs4OSS#6]
能够介绍一下部署的需要的环境吗
部署php5.6+nginx 1.10 完成后提示
![image](https://user-images.githubusercontent.com/20279456/49124437-68915900-f2f7-11e8-9b8e-0cb1d8af1579.png)

**Comment by YXuuan** [comment]
这个应该是配置文件没调整好，你按F12看一下控制台的报错看一下。
